COMPONENT_MAP={
'4 passos para otimizar o modelo (instancia modelo. ajusta modelo. prevê)': 'Otimização',
'API Economy': 'Fontes de dados',
'APIs': 'Fontes de dados',
'APIs em geral': 'Fontes de dados',
'ARIMA': 'Séries temporais/Algoritmo',
'ARIMA. SARIMAX e Prophet': 'Séries temporais/Algoritmo',
'Acesso e processamento de APIs': 'Fontes de dados',
'Algoritmos de Classificação': 'Classificação',
'Algoritmos de classificação': 'Classificação',
'Algoritmos enviezados': 'Viés',
'Amostra': 'Amostra',
'Amostragem': 'Amostra',
'Análise Bivariada': 'Estatística',
'Análise End to End (prática)': 'EDA',
'Análise de viés. overfitting e otimização do erro': 'Viés/variância',
'Aplicabilidade da regressão logística': 'Regressão logística/Algoritmo',
'Aplicação de Digital Analytics no mercado': 'Digital Analytics',
'Aplicação de PCA para solucionar problemas de negócio': 'Negócios/Algoritmo',
'Aplicação de modelos lineares': 'Regressão',
'Aplicação de regressão múltipla': 'Regressão',
'Aplicação de testes de hipótese': 'Teste de hipótese',
'Aplicação em código com redução Componentes Principais': 'Data compression',
'Aplicações de Conceitos no Negócio': 'Negócios',
'Aplicações do mundo real': 'Negócios',
'Aplicações práticas de inferência': 'Estatística inferencial',
'Apresentação Desafio 1': 'Aplicação',
'Arquitetura de dados': 'Arquitetura de dados',
'As diversas formas de acessar dados': 'Fontes de dados',
'Automated Feature Engineering': 'Feature engineering',
'Avaliação do Modelo': 'Validação',
'BI Archtecture (Data Sources. Staging Area. Warehouse. Data Marts)': 'Arquitetura de dados',
'BI vs BIG DATA': 'Arquitetura de dados',
'Bag of Words': 'NLP',
'Banco de Dados': 'Bancos de dados',
'Banco de Dados. Data Warehouses e Data Lakes': 'Arquitetura de dados',
'Bancos de Dados': 'Banco de dados',
'Base teórica para Análise de Componente Principal': 'Data compression/Algoritmo',
'BigData. SQL. NoSQL': 'Banco de dados',
'Busca de melhor erro dividindo os dados entre treino e teste': 'Otimização',
'Business (Cases de uso dos modelos)': 'Negócios',
'Business Question': 'Data Analytics',
'Calculando o Otimizador e o Estimador da regressão': 'Regressão',
'Calculando o R quadrado e o Beta1': 'Regressão',
'Cases de Classificação': 'Classificação',
'Cases de clusterização': 'Agrupamento/Aplicação',
'Classificadores2': 'Classificação',
'Clustering': 'Agrupamento',
'Clusterização': 'Agrupamento',
'Clusterização .': 'Agrupamento',
'Clusterização não supervisionada com K-Means': 'Agrupamento/Algoritmo/ML',
'Coeficiente de determinação (R²)': 'Regressão/otimização',
'Como carregar diferentes bases de dados e fazer relacionamentos entre elas no Tableau': 'Tableau',
'Como consumir dados via APIs': 'Fontes de dados',
'Como contar histórias com dados': 'Storytelling',
'Como escolher o melhor modelo (stepwise)?': 'Otimização',
'Como gerar visualizações de dados no Tableau': 'Tableau',
'Como verificar o estacionarismo de uma série temporal': 'Séries temporais',
'Componente principal (PCA)': 'Data compression/Algoritmo/ML',
'Componentes e Características de Time Series': 'Séries temporais',
'Compreensão dos dados em relação ao domínio/contexto': 'EDA',
'Conceito de Distribuição de Probabilidade': 'Probabilidade',
'Conceito de tudo mais constante (Ceteris Paribus)': 'Princípios de análise',
'Conceitos básicos de Machine Learning': 'ML',
'Conceitos de underfitting e overfitting': 'Regressão',
'Construção de Dashboards': 'DataViz',
'Construção de Tabelas': 'Arquitetura de dados',
'Construção e execução de queries': 'SQL/Ferramenta',
'Controle Sintético': '?',
'Correlação e Covariância': 'Estatística descritiva',
'Correlação entre variáveis': 'Estatística descritiva',
'Covariância e Correlação': 'Estatística descritiva',
'Craição de APIs.': 'API (dev)',
'Crescimento da influência algorítmica na sociedade': 'Cultura de dados',
'Criação de novas variáveis': 'Data wrangling',
'Criação de tabela': 'Arquitetura de dados',
'Cubo de Dados': 'Arquitetura de dados',
'Cuidados ao usar a distância euclidiana (escala das variáveis)': 'Distância',
'Cultura Data-Driven': 'Cultura de dados',
'Curva ROC': 'Classificação/Otimização',
'Curva ROC e AUC': 'Classificação/Otimização',
'Cálculo de Probabilidades e Lei dos Grandes Números': 'Estatística inferencial',
'Cálculo de z-score e intervalo de confiança': 'Estatística inferencial',
'DBScan': 'Agrupamento/Algoritmo/ML',
'DSP (Data Science Pipeline) 9 steps': 'DS pipeline',
'Dask': 'Deploy',
'Data Compression': 'Data compression',
'Data Miner': 'Data mining',
'Data Miner (Captura dos dados)': 'Fontes de dados',
'Data Studio': 'Google Data Studio/Ferramenta',
'Data Tracking Sheet': 'Fontes de dados',
'Data Warehouse. Data Lake. Business Intelligence': 'Arquitetura de dados',
'Data economy': 'Cultura de dados',
'DataFrame': 'Ferramenta',
'Data_Driven Culture': 'Cultura de dados',
'Decision Trees': 'Árvores de decisão/Algoritmo/ML',
'Declaraçao DML': 'DML',
'Deep-Dive': '?',
"Definição de Métricas e KPI's": 'Data Analytics/métricas',
'Definição do intervalo de confiança': 'Estatística inferencial',
'Delete': 'Ferramenta',
'Dependências': 'Ferramenta',
'Desafio': 'Aplicação',
'Desafio III': 'Aplicação',
'Desafio1': 'Aplicação',
'Desvio padrão': 'Estatística descritiva',
'Diferença das diferenças': '?',
'Diferença entre "pensar" e "fazer" Ágil': 'Agile',
'Diferença entre API e Scrapping': 'Fontes de dados',
'Diferenças entre as cerimônias do SCRUM': 'Agile',
'Digital Analytics': 'Data Analytics',
'Dispersão': 'Dispersão',
'Distrbuições desbalanceadas': 'Resampling',
'Distribuição Exponencial e de Poisson': 'Probabilidade',
'Distribuição de Bernoulli e Binomial': 'Probabilidade',
'Distribuição de Probabilidade e Normal': 'Probabilidade',
'Distribuição de Weibul e Normal': 'Probabilidade',
'Distribuição normal': 'Probabilidade',
'Distribuições de Probabilidade': 'Probabilidade',
'Docker': 'Deploy/DevOps',
'ETL': 'ETL',
'ETL com Open Refine': 'ETL',
'ElasticNet': 'Regressão/Otimização',
'Elementos visuais de percepção': 'DataViz',
'Eli5 para interpretar modelos white-box': 'Debugging',
'Encontrar informações no Google Analytics': 'Marketing digital',
'Ensemble': 'Ensembles/Algoritmo/ML',
'Ensemble (bagging. boosting. stacking)': 'Ensembles/Algoritmo/ML',
'Ensemble02': 'Ensembles/Algoritmo/ML',
'Ensembles': 'Ensembles/Algoritmo/ML',
'Entrevistas de BI': 'Data Analytics',
'Entropia': 'Otimização/Métricas',
'Escolha do tema': 'Projeto integrador',
'Estimativa de Coeficientes': 'Regressão',
'Estrutura da URL': 'Fontes de dados',
'Estrutura de Informação': 'Fontes de dados',
'Estrutura de informações': 'Fontes de dados',
'Estrutura do HTML e WebServer': 'API (dev)',
'Evolução de consensos morais e éticos': 'LGPD',
'Evolução dos consensos sobre ética': 'LGPD',
'Evolução dos consensos sobre ética?': 'LGPD',
'Execução de um modelo preditivo (IMDB)': 'Classificação',
'Exploração de dados': 'EDA',
'Extração de dados via Scrapping': '',
'FAC e FACP': 'Séries temporais',
'FBProphet': 'Séries temporais',
'Fases de Entrega': '?',
'Feature Engineering': 'Feature engineering',
'Feature Tools': 'Feature engineering',
'Ferramentas de Digital Analytics': 'Digital analytics',
'Fontes de estudo de ciência de dados': 'Referências',
'Framework Scrum': 'Agile',
'Framework de BI': 'Data Analytics',
'Frameworks de Gestão de Portfólio': 'Data Analytics',
'Frameworks de Gestão de Roadmap': 'Management',
'Fundamentos do MySQL': 'Bases de dados/Ferramenta',
'Função de custo': 'Otimização',
'GDPR': 'LGPD',
'GDPR (General Data Protection Regulation)': 'LGPD',
'Geração de gráficos': 'DataViz',
'Google Analytics': 'Digital Analytics/Ferramenta',
'Google Analytics gerando insights para seu negócio': 'Ferramenta',
'Google Tag Manager': 'Digital Analytics/Ferramenta',
'Gradiente Descendente': 'Otimização',
'Gradiente descendente': 'Otimização',
'Graphviz': 'DataViz/Ferramenta',
'Grid search': 'Otimização/Algoritmo',
'Gráficos': 'DataViz',
'HTML': 'Fontes de dados',
'HTTP: método de comunicação e respostas': 'Fontes de dados',
'Histogramas': 'Estatística descritiva',
'Holt-Winters': 'Séries temporais/Algoritmo',
'IF em SQL': 'SQL/Ferramenta',
'Impactos do Ágil em Gestão Orçamentária': 'Agile',
'Impactos do Ágil em Gestão Orçamentária?': 'Agile',
'Importância e aplicação de proteção de dados na sua empresa': 'LGPD',
'Inferencia': 'Estatística inferencial',
'Inferência': 'Estatística inferencial',
'Inferência Estatística': 'Estatística inferencial',
'Inferência de duas médias (t-test)': 'Estatística inferencial',
'Inferência estatística': 'Estatística inferencial',
'Inferência estatística e teste de hipótese': 'Estatística inferencial',
'Inferência usando z-score': 'Estatística inferencial',
'Inferência1': 'Estatística inferencial',
'Infra-estrutura para dados': 'Arquitetura de dados',
'Infraestrutura paralela de processamento em produção': 'Arquitetura de dados',
'Insert': 'SQL/Ferramenta',
'Instrução SELECT (WHERE. ORDER BY)': 'SQL/Ferramenta',
'Interpretação dos resultados Regressão Logística': 'Regressão logística/classificação',
'Interpretação dos resultados da regressão logística': 'Regressão logística/classificação',
'Intervalo de Confiança': 'Estatística inferencial',
'Intervalo de confiança': 'Estatística inferencial',
'Introdução às ferramentas: Python. Anaconda. Jupyter e Git?': 'Ferramenta',
'JSON': 'Fontes de dados',
'Joins em SQL': 'SQL/Ferramenta',
'K-Means': 'Agrupamento/Algoritmo/ML',
'KMeans': 'Agrupamento/Algoritmo/ML',
'KPI': 'Métricas',
"KPI's": 'Métricas',
'LGPD': 'LGPD',
'LGPD (Lei Geral de Proteção de Dados)': 'LGPD',
'LGPD e GDPR': 'LGPD',
'LIME para interpretar modelos black-box': 'Interpretação/ferramenta',
'LSTM (Long Short Term Memory)': 'NN/Algoritmo',
'Lasso': 'Otimização',
'Lei dos Grandes números': 'Estatística inferencial',
'MSE e RMSE': 'Otimização',
'MVP': 'Negócios',
'MYSQL': 'Bancos de dados/Ferramenta',
'Machine Learning': 'ML',
'Manipulação de dados': 'EDA',
'Manipulação de dados com Pandas': 'EDA/Ferramenta',
'Matplotlib': 'DataViz/Ferramenta',
'Matriz de Confusão': 'Estatística inferencial',
'Matriz de confusão (erro tipoI e erro tipo II)': 'Estatística inferencial',
'Mean Shift': 'Agrupamento/Algoritmo/ML',
'MeanShift e DBSCAN': 'Agrupamento/Algoritmo/ML',
'Medidas de Associação': 'Estatística descritiva',
'Medidas de Centralidade': 'Estatística descritiva',
'Medidas de Dispersão': 'Estatística descritiva',
'Medidas de Tendência Central (Desvio Padrão.variância...)': 'Estatística descritiva',
'Medidas de associação: Covariância e Correlação': 'Estatística descritiva',
'Medidas de dispersão: desvio-padrão. variância': 'Estatística descritiva',
'Medidas de tendência': 'Estatística descritiva',
'Metas': 'Negócios',
'Metodologia': 'Agile',
'Metodologias Ágeis': 'Agile',
'Metricas': 'Métricas',
'Modelagem Estatística': 'Modelagem',
'Modelagem Estatística - Regressão Linear': 'Regressão',
'Modelagem com regressão logística': 'Regressão logística/Classificação',
'Modelagem de Banco de dados': 'Arquitetura de dados',
'Modelagem de banco de dados': 'Arquitetura de dados',
'Modelagem de dados': 'Modelagem',
'ModelagemEstatistica2_Regressão': 'Regressão',
'ModelagemEstatística3_Regressão': 'Regressão',
'Modelos de Classificação do SciKit Learn': 'Classificação',
'Média Móvel': 'Séries temporais',
'Média. Moda e Mediana em Python': 'Estatística descritiva',
'Método Aditivo e Multiplicativo de decomposição da TimeSeries': 'Séries temporais',
'Métricas (precision. recall. specificity. F1Score)': 'Otimização/Métricas',
'Métricas de Digital Analytics': 'Digital Analytics/Métricas',
'Métricas de avaliação dos modelos (acuracidade. precisão. recall)': 'Avaliação/Métricas/Modelagem',
'Métricas e Dimensões': 'Métricas',
"Métricas e KPI's": 'Métricas',
'Métricas e KPIS': 'Métricas',
'N-gram': 'NLP/Algoritmo/ML',
'NLP': 'NLP',
'NLP (Natual Processing Language)': 'NLP',
'NPL - Processamento de Linguagem Natual': 'NLP',
'Naive Bayes': 'Modelagem/Algoritmo/ML',
'NoSQL': 'Bancos de dados',
'Normalização dos dados': 'EDA',
'Normalização dos dados (log. desvio padrão)': 'EDA',
'Normalização e Padronização': 'EDA',
'Novas formas de visualização': 'DataViz',
'Noções básicas de Python': 'Ferramenta',
'O crescimento da influência dos algoritmos na sociedade': 'Cultura de dados',
'O crescimento da influência dos algoritmos na sociedade?': 'Cultura de dados',
'O impacto da escolha das variáveis nas métricas de validação': 'Avaliação',
'Operações Numéricas': 'Ferramenta',
'Otimizadores': 'Otimização',
'Otimização de Parâmetros': 'Otimização',
'Outlier': 'Estatística descritiva',
'Outliers': 'Estatística descritiva',
'PCA': 'Compressão de dados/Algoritmo/ML',
'PCA (Principal Component Analysis)': 'Compressão de dados/Algoritmo/ML',
'Padronização de escala (StandardScaler)': 'Data preparation',
'Pandas': 'Ferramenta',
'Pandas em geral': 'Ferramenta',
'Papeis e responsabilidades no SCRUM': 'Agile',
'Papel transformador da tecnologia': 'Cultura de dados',
'Papel transformador da tecnologia?': 'Cultura de dados',
'Para que serve a técnica de Gradiente Descendente': 'Otimização',
'Paradoxo de Simpson': 'Estatística inferencial',
'Paradoxos estatísticos': 'Estatística inferencial',
'Parametro autoregressivo (p). Número de diferenças para estacionarizar (d). número de médias móveis (q)': 'Séries temporais',
'Perfil de Equipe': '?',
'Pipeline': 'Pipeline',
'Pontos de sucesso e fracasso em implantação ágil': 'Agile',
'PowerBI': 'Ferramenta',
'Preparação de dados': 'Data preparation',
'Previsão de Diabetes': 'Classificação/Aplicação',
'Princípios da metodologia ágil': 'Agile',
'Probabilidade': 'Probabilidade',
'Probabilidade Condicional e Teorema de Bayes': 'Probabilidade',
'Probabilidade condicional': 'Probabilidade',
'Processo de Digital Analytics': 'Digital Analytics',
'Projeto Integrador': 'Aplicação',
'Projeto integrador': 'Aplicação',
'Propósito do Produto/projeto Digital': 'Negócios',
'Protocolo HTTP': 'Fontes de dados/Ferramenta',
'Python': 'Ferramenta',
'R quadrado': 'Regressão/Avaliação',
'RNN (Recurrent Neural Networks)': 'NN/Algoritmo/ML',
'Random Forest': 'Classificação/Algoritmo/ML',
'Redes Convolucionais': 'NN/Algoritmo/ML',
'Redes Neurais': 'NN/Algoritmo/ML',
'Redução de Dimensionalidade': 'Compressão de dados',
'Redução de dimensionalidade': 'Compressão de dados',
'Regressao Linear Simples': 'Regressão',
'Regressão Linear': 'Regressão',
'Regressão Linear ?': 'Regressão',
'Regressão Linear com API scikit-learn': 'Regressão/Ferramenta',
'Regressão Logistica': 'Classificação',
'Regressão Logística': 'Classificação',
'Regressão Logística 2': 'Classificação',
'Regressão Multipla': 'Regressão',
'Regressão Múltipla': 'Regressão',
'Regressão linear': 'Regressão',
'Regressão linear e minimização dos erros': 'Regressão',
'Regressão múltipla': 'Regressão',
'Regressões para resolver problemas de negócio': 'Regressão/Aplicação',
'Regularização': 'Regularização',
'Regularização com Ridge e Lasso': 'Otimização/Algoritmo',
'Regularização por Feature Engineering': 'Otimização',
'Revisão da metodologia de análise de dados': 'Metodologia/Data Analytics',
'Revisão estatística descritiva e curva normal': 'Estatística descritiva/Probabilidade',
'Revolução Ágil': 'Agile',
'Ridge': 'Otimização/Algoritmo',
'Roadmap': 'Roadmap',
'R² ajustado': 'Avaliação/Modelagem',
'SCRUM': 'Agile',
'SELECT': 'SQL/Ferramenta',
'SELECT. GROUPBY. ORDER. JOIN': 'SQL/Ferramenta',
'SGBD (Sistema gerenciador de banco de dados)': 'Bancos de dados',
'SGBDs em geral': 'Bancos de dados',
'SHAP': 'Modelagem/Interpretação',
'SQL': 'SQL/Ferramenta',
'SQL - JOINS (Inner. left/right. outer)': 'SQL/Ferramenta',
'SQL vs NoSQL': 'SQL',
'SQL_NoSQL': 'Bancos de dados',
'SQLite': 'Bancos de dados/Ferramenta',
'Scraping': 'Fontes de dados/Ferramenta',
'Scraping - Aula Pratica': 'Fontes de dados/Aplicação',
'Scrapping com Selenium': 'Fontes de dados/Aplicação',
'Scrum': 'Agile',
'Segurança da informação': 'LGPD',
'Selenium': 'Fontes de dados/Ferramenta',
'Series Temporais': 'Séries temporais',
'Simulações de Monte Carlo': 'Modelagem/Algoritmo/Estatística inferencial',
'Simulações de probabilidades em Python': 'Probabilidade/Ferramenta',
'Spark': 'Arquitetura de dados/Ferramenta',
'Storytelling': 'Storytelling',
'Subqueries em SQL': 'SQL/Ferramenta',
'Tableau': 'Ferramenta',
'Tableau e suas funcionalidades': 'Ferramenta',
'Tagueamento': 'Digital Analytics',
'Tendências de BI para 2019': 'Data Analytics/Tendências',
'Teorema de Bayes': 'Probabilidade',
'Teorema do Limite Central': 'Estatística inferencial',
'Teoria por trás de clusterização não supervisionada': 'Agrupamento',
'Teste de Hipótese': 'Teste de hipótese',
'Teste de Hipóteses': 'Teste de hipótese',
'Teste de hipótese': 'Teste de hipótese',
'Teste t com duas amostras': 'Teste de hipótese',
'Testes de Hipóteses': 'Teste de hipótese',
'Threshold': 'Otimização',
'Threshold (Limite)': 'Otimização',
'Time Series': 'Séries temporais',
'Times de Dados': 'Agile',
'Tipos de sistemas de recomendação (Recuperação direta. Filtragem de conteúdo. Filtragem colaborativa)': 'Sistemas de recomendação/ML',
'Tomada de decisão': 'Data Analytics',
'Trade off entre viés e variância': 'Viés/variância',
'Transformar uma série temporal em estacionária': 'Séries temporais',
'Transformação de regressão linear para logística': 'Regressão',
'Transformação em dummies/categóricas': 'Data preparation',
'Transformação logarítimica e exponencial': 'Data wrangling',
'Transformação logarítimica para normalização de distribuição': 'Data wrangling',
'Tratamento de dados com Pandas': 'Ferramenta',
'Treino de Pandas': 'Ferramenta',
'Treino e teste para validação': 'Avaliação',
'Tráfego': '?',
'Tudo pode ser medido': 'Data Analytics',
'Tuning Models': 'Otimização',
'Técnica de Cross Validation': 'Validação',
'Técnicas de Gradiente Descendente para diminuir o erro de algoritmos de Machine Learning': 'Otimização',
'Técnicas de oversampling e undersampling': 'Resampling',
'Union em SQL': 'SQL/Ferramenta',
'Update': 'SQL/Ferramenta',
'Uso das APIs': 'Fontes de dados',
'Uso de algoritmos supervisionados e não supervisionados': 'ML',
'Uso dos diferentes tipos de gráficos': 'DataViz',
'Usos legais de dados': 'LGPD',
'Validando o Forecasting': 'Validação',
'Validação de Modelos': 'Validação',
'Variação no modelo': 'Otimização',
'Variância e Desvio Padrão': 'Medidas de dispersão',
'Verificar se as datas estão completas': 'Data cleaning',
'Visualização de dados com Pandas': 'DataViz',
'Visão Computacional': 'Visão computacional',
'Viés': 'Viés/variância',
'Viés aleatório e sistemático': 'Viés/Variância',
'WHERE (filtros)': 'SQL/Ferramenta',
'Webscrapping utilizando o Beautifulsoup': 'Fontes de dados/Ferramenta',
'White noise': 'Séries temporais',
'XGBoost. FBProphet a ARIMA': 'Séries temporais/Algoritmo/ML',
'Xpath': 'Fontes de dados',
'a aplicabilidade/consequências da Lei de Proteção de Dados (LGPD) em Data Analytics': 'LGPD',
'a aplicabilidade/consequências da Lei de Proteção de Dados em Data Analytics': 'LGPD',
'a biblioteca BeautifulSoup': 'Fontes de dados/Ferramenta',
'a biblioteca Spacy': 'NLP',
'a criação básica de gráficos no Tableau': 'Tableau/Ferramenta',
'a criação e a reaplicação de receitas de transformação de dados': 'Data wrangling',
'a definição de KPIs': 'KPI',
'a definição de métricas e KPIs para mensurar resultados': 'KPI',
'a diferença do scrum e do kanban': 'Agile',
'a estrutura de informação para criação de dashboard no processo data analytics': 'Data Analytics',
'a estrutura de informações num processo de data analytics': 'Data Analytics',
'a estruturação da base de dados (modelo relacional)': 'Arquitetura de dados',
'a função IF no SQL': 'SQL/Ferramenta',
'a função VIEW': 'SQL/Ferramenta',
'a importância da entrega incremental': 'Agile',
'a importância da legislação de dados': 'LGPD',
'a importância da privacidade de dados': 'LGPD',
'a importância de escolher as variáveis do modelo': 'Modelagem',
'a importância de planejamento no product backlog e no sprint backlog': 'Agile',
'a importância de se planejar para apresentar dados': 'Storytelling',
'a importância do processo de ETL': 'ETL',
'a influência dos elementos visuais em visualização de dados': 'DataViz',
'a influência dos vieses na coleta e análise de dados': 'Viés/variância',
'a influência e função dos elementos visuais em visualização de dados': 'DataViz',
'a interface do PowerBI': 'Power BI/Ferramenta',
'a interface do Tableau': 'Tableau/Ferramenta',
'a interpretação de como os βs  podem influenciar a sua variável dependente': 'Regressão',
'a interpretação do r²': 'Regressão',
'a metodologia de análise de dados': 'Cultura de dados',
'a similaridade entre funções de SQL e Pandas': 'Ferramenta',
'a técnica de Cross-Validation (validação) nos modelos de predição': 'Validação',
'a técnica de regularizção': 'Otimização',
'a técnica de sprints': 'Agile',
'a utilização do pacote statsmodel': 'Estatística',
'abordagens de machine learning': 'ML',
'agrupamento de registros': 'Ferramenta',
'algoritmos de classificação': 'Classificação',
'amostragem de dados': 'Amostra',
'analise bivariada': 'Estatística',
'analise de sentimentos utilizando uma rede neural': 'NLP',
'análise bivariada': 'Estatística',
'análise bivariada (correlação)': 'Medidas de associação',
'análise de dados com Pandas': 'Ferramenta',
'análise de dados para embasar tomadas de decisão': 'Data Analytics',
'análise de importância das variáveis para aumento/diminuição da probabilidade': 'Interpretação',
'análise descritiva': 'Estatística',
'análise estatística': 'Estatística',
'análises estatísticas no excel': 'Estatística',
'análises estatísticas para geração de insights': 'Data Analytics',
'aplicar o seu mindset analítico em um caso real': 'Data Analytics',
'aplicação da metodologia nos diferentes escopos de trabalho': 'Agile',
'aplicação de Random Forrest com Ensembles': 'Ensembles/Algoritmo/ML',
'aplicação de análise de dados para problemas de negócio': 'Negócios',
'aplicação de análise de dados para problemas de negócio?': 'Negócios',
'aplicação de conceitos estatísticos': 'Estatística',
'aplicação de conceitos estatísticos para análise de dados': 'Estatística',
'aplicação de diferentes conceitos de Data Analytics para construção de análise': 'Data Analytics',
'aplicação de digital analytics em diferentes mercados': 'Data Analytics',
'aplicação de intervenção de dados para solução de problemas reais': 'Negócios',
'aplicação de modelos de Boosting': 'Boosting/Algoritmo/ML',
'aplicação de modelos de classificação': 'Classificação',
'aplicação de modelos para forecasting': 'Séries temporais',
'aplicação de métricas': 'KPI',
'aplicação de técnincas  de Ensembles': 'Ensembles',
'aplicação do PCA': 'Data compression/Algoritmo/ML',
'aplicação do conhecimento no Desafio': 'Aplicação',
'aplicação para solucionar problemas binários': '?',
'aplicação prática das APIs': 'Fontes de dados',
'aplicação prática de séries temporais': 'Séries temporais',
'aplicação prática dos conceitos aprendidos': 'Aplicação',
'aplicações': 'Aplicação',
'aplicações Práticas das Distribuições': 'Distribuição de probabilidade',
'aplicações das extração de dados': 'Fontes de dados',
'aplicações de Machine Learning': 'ML',
'aplicações de clusterização de dados': 'Agrupamento',
'aplicações de conceitos de análises de dados em negócios': 'Negócios',
'aplicações de distribuição': 'Distribuição de probabilidade',
'aplicações de ensembles': 'Ensembles/Algoritmo/ML',
'aplicações de sistemas de recomendação': 'Sistemas de recomendação/Algoritmo/ML',
'aplicações e cuidados do machine learning no mundo real': 'ML',
'aplicações e possibilidades da inteligência de dados': 'Cultura de dados',
'aplicações práticas': '?',
'apresentação do desafio 4': 'Aplicação',
'aquisição de dados para estratégias de negócio': 'Negócios',
'arvores de decisão': 'Árvores de decisão/Algoritmo/ML',
'as cerimônias do scrum': 'Agile',
'as diferentes opções de exportar. compartilhar e publicar worksheets do Tableau': 'Tableau/Ferramenta',
'as diferentes técnicas de elaboração das perguntas de negócios': 'Data Analytics',
'as diferentes técnicas de elaboração das perguntas de negócios (business questions)?': 'Research',
'as diferenças entre ferramentas de BI': 'Ferramenta',
'as funções PROCEDURE e VIEW': 'SQL/Ferramenta',
'as funções agregadoras: COUNT. AVG. SUM. MAX. MIN': 'SQL/Ferramenta',
'as funções básicas do Power BI': 'Ferramenta',
'as funções básicas do PowerBI': 'Ferramenta',
'as medidas de centralidade': 'Medidas de centralidade',
'as medidas de dispersão': 'Medidas de dispersão',
'assessment de Digital Analytics': 'Research',
'autocorrelação (ACF) e autocorrelação parcial (PACF)': 'Séries temporais',
'autocorrelação serial': 'Séries temporais',
'automated feature engineer': 'Data wrangling',
'automated feature selection': 'Data wrangling',
'automatizando a coleta de dados do site': 'Fontes de dados',
'backlog': 'Agile',
'bagging': 'Boosting',
'bagging. boosting & stacking': 'Boosting',
'balanceamento': 'Resampling',
'beautifulsoup': 'Fontes de dados/Ferramenta',
'benefício marginal e aplicação': 'Negócios',
'bibliotecas de geração de gráficos': 'DataViz',
'boosting': 'Boosting',
'boxplot e histograma': 'EDA',
'business cases': 'Negócios',
'business questions': 'Negócios',
'captura de dados': 'Fontes de dados',
'carga de dados e alter table no mysql': 'SQL/Ferramenta',
'cases': 'Negócios',
'causalidade': 'EDA',
'chave primária (PK) e chave estrangeira (FK)': 'Arquitetura de dados/Ferramenta',
'clustering por centroid. contagem de pontos e densidade (K-means. Mean-Shift. DBSCAN)': 'Agrupamento/Algoritmo/ML',
'clusterização': 'Agrupamento',
'co-variância e correlação': 'Medidas de associação',
'codificação em Python': 'Ferramenta',
'coeficiente de determinação R quadrado': 'Regressão',
'comandos DML: SELECT.  WHERE. ORDER BY. LIMIT': 'SQL/Ferramenta',
'comandos de Agregação e Agrupamento: COUNT. SUM. MAX. MIN. AVG. GROUP BY. HAVING': 'Ferramenta',
'como a LSTM lida com curto e longo prazos': 'NN/Algoritmo/ML',
'como abordar problemas de negócio e apresentar intervenções para resolução desses problemas': 'Research',
'como analisar uma base de dados e criar um dashboard para tomada de decisão': 'DataViz',
'como aplicar a metodologia de data analytics em problema de negócio': 'Research',
'como aplicar o shapley value': 'Interpretação',
'como aplicar os filtros no dataset: de texto. data e valores': 'ETL',
'como atacar o problema do seu Projeto Integrador': 'Aplicação',
'como atacar problemas com ciência de dados': 'Cultura de dados',
'como atacar um problema em Ciência de Dados': 'Cultura de dados',
'como atingir diferentes públicos com a mesma história': 'Storytelling',
'como captar dados via API': 'Fontes de dados',
'como capturar os dados (fontes de dados)': 'Fontes de dados',
'como conectar de diferentes bases de dados dentro do Tableau': 'Ferramenta',
'como conectar e integrar diferentes fontes de dados no Tableau': 'Ferramenta',
'como construir uma história com dados ou sobre eles': 'Storytelling',
'como construir uma narrativa': 'Storytelling',
'como construir uma narrativa com dados': 'Storytelling',
'como consumir APIs': 'Fontes de dados',
'como contextualizar e estruturar o storytelling do seu projeto': 'Storytelling',
'como copiar registros de uma tabela no SQL': 'SQL/Ferramenta',
'como criar campos calculados. cálculos de tabela e parâmetros no Tableau': 'Tableau/Ferramenta',
'como criar colunas para resolver um problema': 'SQL/Ferramenta',
'como criar e editar Dashboards no Tableau': 'Tableau/Ferramenta',
'como criar uma tabela no SQL': 'SQL/Ferramenta',
'como encontrar os Highlights e Insights para tomada de decisão por dados': 'Data Analytics',
'como escolher corretamente os gráficos para os seus relatórios': 'DataViz',
'como estacionarizar series temporias': 'Séries temporais',
'como explorar os dados com o Mostre-me no Tableau': 'Tableau/Ferramenta',
'como fazer diferentes tipos de gráficos: Linha. barra. histogram. Bubble. Tree map': 'DataViz',
'como fazer relacionamentos entre tabelas no SQL': 'SQL/Ferramenta',
'como funciona a visão computacional': 'Visão computacional',
'como funciona o shapley value': 'Interpretação',
'como funciona o stacking': '?',
'como funcionam as regressões': 'EDA',
'como inserir. apagar e atualizar registros e colunas no SQL': 'SQL/Ferramenta',
'como integrar o problema com a análise de dados': 'Cultura de dados',
'como interpretar. estruturar. coletar dados e trazer análise crítica para problemas de negócio': 'Cultura de dados',
'como mapear os dados necessários para resolver problemas de negócio': 'Cultura de dados',
'como melhorar a legibilidade do código o uso de AS e comentários': 'SQL/Ferramenta',
'como ordenar os dados nos gráficos do Tableau': 'Tableau/Ferramenta',
'como podemos conseguir dados para medir e analisar': 'EDA',
'como publicar um dashboard no Tableau': 'Tableau/Ferramenta',
'como realizar SUBQUERY em SQL': 'SQL/Ferramenta',
'como realizar mudanças em tabelas no SQL': 'SQL/Ferramenta',
'como rodar uma rede neural que entende imagens': 'NN/Algoritmo/ML',
'como rodar uma regressão para responder uma pergunta real': 'Regressão',
'como são os desafios reais': 'Negócios',
'como trabalhar com valores NULL': 'Data cleaning',
'como trabalhar uma base de dados a fim de gerar insights para tomadas de decisão': 'EDA',
'como transformar o resultado das APIs em dataframes': 'EDA',
'como usar os filtros no Tableau': 'Tableau/Ferramenta',
'como utilizar visualização': 'DataViz',
'comparação de modelos de Boosting': 'Ensembles/Algoritmo/ML',
'composição de um time de dados': 'Negócios',
'compressão de dados': 'Compressão de dados',
'computação paralela': 'Arquitetura de dados',
'conceitos basicos de visualização': 'DataViz',
'conceitos de análise e métricas e sua importância negócios digitais': 'Métricas/Negócios',
'construção de APIs com flask': 'API (dev)',
'construção de business question': 'Negócios',
'construção de narrativa para comunicar de dados e ideias': 'Storytelling',
'construção de reports para tomada de decisão': 'DataViz',
'contrução de narrativas em data analytics': 'Storytelling',
'converter modelo entidade relacionamento para modelo relacional': 'Arquitetura de dados',
'correlação': 'Estatística descritiva',
'correlação e causalidade': 'Análise',
'correlações espúrias e causalidade': 'Análise',
'covariância': 'Estatística descritiva',
'criar histórias com o Tableau': 'Storytelling/Ferramenta',
'criação de dashboards no Tableau': 'DataViz/Ferramenta',
'criação de variáveis (feature engineering)': 'Feature engineering',
'criação e alteração de tabelas em SQL': 'Arquitetura de dados/Ferramenta',
'critério de quebra das árvores de decisão': 'Árvores de decisão/Algoritmo/ML',
'cross validation': 'Otimização',
'cultura Data-driven': 'Cultura de dados',
'cultura anaítica': 'Cultura de dados',
'cultura data-driven': 'Cultura de dados',
'curva ROC e por que usar': 'Otimização',
'curva densidade de probabilidade e Tipos de Distribuições': 'Probabilidade',
'custom loss function': 'Métricas/Otimização',
'customização da Loss Function': 'Métricas/Otimização',
'cáculo de probabilidades': 'Probabilidade',
'cálculos de probabilidade': 'Probabilidade',
'dados e bases de dados': 'Bancos de dados',
'data storytelling': 'Storytelling',
'data tracking sheet': 'Análise',
'data warehouse': 'Arquitetura de dados',
'declarações DML (CREATE. INSERT. DELETE. UPDATE. TRUNCATE)': 'SQL/Ferramenta',
'declarações DML: INSERT. UPDATE. DELETE': 'SQL/Ferramenta',
'definição de métricas e KPIs para mensurar resultados': 'Métricas',
'definição de métricas e KPI’s': 'Métricas',
'definição de métricas e kpis': 'Métricas',
'desafio kaggle': 'Aplicação',
'desvio-padrão e variância': 'Estatística descritiva',
'diferentes formas de captação de dados': 'Fontes de dados',
'diferentes métricas de digital analytics': 'Digital Analytics',
'diferentes tipos de gráficos': 'DataViz',
'diferença do scrum e do kanban': 'Agile',
'diferença entre a biblioteca selenium e requests': 'Fontes de dados',
'dimensão da cultura data driven': 'Cultura de dados',
'dimensões': 'Dimensões',
'distribuição de probabilidades': 'Probabilidade',
'distribuição normal': 'Probabilidade',
'distribuição normal (curva de Gauss)': 'Probabilidade',
'distribuição normal. bernoulli. poisson e exponencial': 'Probabilidade',
'distribuições de probabilidade': 'Probabilidade',
'distribuições de probabilidades': 'Probabilidade',
'distribuições em Python': 'Probabilidade/Ferramenta',
'distribuições estatísticas': 'Probabilidade',
'diversas abordagens de machine learning': 'ML',
'driver para controle de navegador': 'Fontes de dados',
'dívida técnica': 'Agile',
'elastic net': 'Regressão/Otimização',
'elementos visuais e itens pré-atentivos': 'DataViz',
'empacotamento de modelos': 'DevOps',
'empatia e UX em análise de dados': 'DataViz/Storytelling',
'empatia em Data Analytics': 'Storytelling',
'encoding e seus impactos ao lidar com dados': 'Encoding',
'encoding vs decoding': 'Encoding',
'endogeneidade e heterocedasticidade': 'Estatística inferencial',
'ensembles': 'Ensembles',
'escolha de variáveis para a Clusterização': 'Agrupamento',
'esqueleto de API': 'Fontes de dados/API',
'estatística com Python': 'Estatística/Ferramenta',
'estilos de gráficos': 'DataViz',
'estratégia de Analytics': 'Estratégia/Data Analytics',
'estrutura de informação para criação de dashboard': 'DataViz',
'estímulos e filtros no Tableau': 'Ferramenta',
'exemplos de aplicação de inferência estatística': 'Estatística inferencial/Aplicação',
'explicabilidade de modelos de Machine Learning': 'Modelagem/Interpretação',
'exploração das bases de dados': 'Bancos de dados',
'exploração de dados': 'Bancos de dados',
'exploração de dados no Tableau': 'Ferramenta',
'extração de dados por uma API': 'Fontes de dados/API',
'extração de dados web': 'Fontes de dados',
'feature engineering': 'Feature engineering',
'ferramenta Análise de Dados do Excel': 'Ferramenta',
'ferramentas de BI': 'Ferramenta',
'ferramentas de análise de dados': 'Ferramenta',
'ferramentas de mineração de dados': 'Data mining/Ferramenta',
'finalidade dos diferentes tipos de gráficos': 'DataViz',
'forma funcional': 'Regressão',
'formas de aquisição de dados': 'Fontes de dados',
'formas éticas de tratamento de dados': 'LGPD',
'framework de scrum': 'Agile',
'frameworks para análise de dados': 'Data Analytics/Frameworks',
'funcionamento de pipeline para modelos em produção.': 'DevOps',
'funcionamento de sistemas de recomendação': 'Sistemas de recomendação/Algoritmo/ML',
'funcionamento de sérieas temporais': 'Séries temporais',
'funcionamento dos algoritmos de clusterização': 'Agrupamento',
'funcionamento e aplicação de NLP': 'NLP/Aplicação',
'função de custo': 'Otimização',
'funções para feature engineerig': 'Feature engieering',
'funções para tratar NULL': 'Data cleaning',
'funções para tratar textos': 'Data cleaning',
'fórmulas avançadas (IF. VLOOKUP. COUNTIFS. SUMIFS…)': 'Ferramenta',
'geração de visualizações no Tableau': 'DataViz/Ferramenta',
'gestão agile': 'Agile',
'gestão de projetos': 'Project management',
'gradiente descendente': 'Otimização',
'gráficos de histograma e boxplot': 'DataViz',
'gráficos e exemplos (escala. proporção. quando usar. onde usar. ...)': 'DataViz',
'heterocedasticidade e homocedasticidade': 'Séries temporais',
'heterogeneidade': '?',
'hipoteses do modelo de regressao': 'Regressão',
'histograma e bloxplot': 'DataViz',
'histogramas em Python': 'DataViz/Ferramenta',
'html': 'Fontes de dados',
'identificar quando os dados precisam de transformação ou não': 'Data cleaning',
'impacto dos dados na vida atual': 'Cultura de dados',
'implementação de sistemas de recomendação': 'Sistemas de recomendação/ML',
'implicações dos algoritmos de machine learning': 'Cultura de dados',
'importancia de fazer Perguntas de Negócios': 'Data Analytics/Negócios',
'importar dados para o SQL': 'SQL/Ferramenta',
'importação de conectores de dados no tableau': 'Fontes de dados/Ferramenta',
'importância da explicação dos modelos black box': 'Modelagem/Interpretação',
'importância do pensamento de negócios em Data Analytics': 'Data Analytics/Negócios',
'importância do pensamento de negócios em Data Analytics?': 'Data Analytics/Negócios',
'importância do processo de ETL': 'ETL',
'inferência estatística': 'Estatística inferencial',
'integração de dados de diferentes data sources no tableau': 'Fontes de dados/Ferramenta',
'interagindo com o navegador': 'Fontes de dados/Ferramenta',
'interpretação da regressão': 'Regressão/Interpretação',
'interpretação das regressões': 'Regressão/Interpretação',
'interpretação de dados e visualizações no tableau': 'Interpretação/DataViz/Ferramenta',
'interpretação de modelos Black-Box': 'Modelagem/Interpretação',
'interpretação do log': 'Data transformation',
'interpretação do output do statsmodel': 'Modelagem/Interpretação/Ferramenta',
'interpretação dos coeficientes da regressão logística': 'Regressão/Interpretação',
'intervalo de confiança': 'Estatística inferencial',
'lasso regression': 'Regressão/Otimização',
'lemmatization e stemming (reduzindo a dimensionalidade do dataset)': 'NLP/Data compression/Algoritmo',
'limpeza de dados com open refine': 'Data cleaning/Ferramenta',
'lógica de programação': 'Lógica/Programação',
'manipulação de dados no Tableau': 'Data manipulation/Ferramenta',
'manipulação de dados no tableau': 'Data manipulation/Ferramenta',
'matriz TF-IDF': 'NLP/Algoritmo',
'matriz de confusão': 'Modelagem/Validação',
'medidas de associação: covariância. correlação. causalidade. correlação linear)': 'Estatística descritiva',
'medidas de centralidade': 'Estatística descritiva',
'medidas de centralidade (média. mediana. moda)': 'Estatística descritiva',
'medidas de centralidade e separatrizes': 'Estatística descritiva',
'medidas de dispersão': 'Estatística descritiva',
'medidas de dispersão (desvio padrão e variância)': 'Estatística descritiva',
'medidas de dispersão (variância. desvio-padrão) e associação (covariância. coeficiente de correlação)': 'Estatística descritiva',
'medidas de variabilidade (variância. desvio padrão. outliers)': 'Estatística descritiva',
'metadados e datatypes': 'Fontes de dados/Programação',
'metodologia de Análise de Dados': 'Data Analytics/Research',
'metodologia de data analytics': 'Data Analytics/Research',
'metodologia para entrega de dashboard': 'DataViz',
'metodologia ágeis': 'Agile',
'modelagem Word 2 Vec': 'NLP/Algoritmo',
'modelagem de Banco de Dados': 'Bancos de dados',
'modelagem de banco de dados': 'Bancos de dados',
'modelagem renda percapita': 'Aplicação',
'modelo TF-IDF': 'NLP/Algoritmo',
'modelo de regressão utilizando scikit-learn': 'Regressão/Ferramenta',
'modelos de Boosting Classificatórios': 'Classificação',
'modelos de Ensembles paralelos': 'Ensembles',
'modelos de classificação': 'Classificação',
'modelos de classificação lineares e não lineares': 'Classificação',
'modelos supervisionados de classificação': 'Classificação',
'modelos ágeis': 'Agile',
'molelos ágeis de trabalho': 'Agile',
'montando uma rede neural': 'NN/Algoritmo/ML',
'montar um dashboard em função floating e suas interações': 'DataViz',
'motivos para utilizar o pickle': 'DevOps/Ferramenta',
'multicolinearidade': 'Regressão',
'média de modelos de Machine Learning': 'ML',
'média. moda e mediana': 'Estatística descritiva',
'métodos básicos (shape. info. describe)': 'EDA/Ferramenta',
'métodos de clusterização': 'Agrupamento',
'métodos de regularização: Lasso. Ridge e ElasticNet': 'Regressão/Otimização',
'métricas': 'Métricas',
'métricas calculadas no Tableau': 'Métricas/Ferramenta',
'métricas de classificação (Precisão. Sensibilidade. curva ROC e AUC)': 'Classificação/Otimização',
'métricas do Google Analytics': 'Digital Analytics/Ferramenta',
'métricas e KPIs': 'Métricas',
'métricas para modelos de classificação': 'Classificação',
'naive bayes': 'Modelagem/Algoritmo',
'normalização dos dados com funções matemáticas (ex: log)': 'Data transformation',
'o Google Analytics': 'Ferramenta',
'o Google Tag Manager': 'Ferramenta',
'o Tableau': 'Ferramenta',
'o Xpath': 'Fontes de dados',
'o ciclo de vida dos dados': 'Cultura de dados',
'o conceito da avaliação do modelo (R ao quadrado ou coeficiente de determinação)': 'Regressão/Avaliação',
'o conceito de convolução': 'Data transformation/Algoritmo',
'o conceito de regressão linear múltipla': 'Regressão',
'o conceito de regressão linear simples': 'Regressão',
'o framework de SCRUM': 'Agile',
'o funcionamento de um neurônio artificial': 'NN',
'o funcionamento de um neurônio da LSTM': 'NN',
'o impacto do problema de negócios nas análises': 'Negócios',
'o mundo da ciencia de dados na vida real': 'Aplicação',
'o potencial das APIs': 'Fontes de dados',
'o processo de Digital Analytics': 'Data Analytics',
'o processo de Transformação no Talend Data Preparation': 'Data transformation/Ferramenta',
'o processo de backlog': 'Agile',
'o processo de extração de dados': 'Fontes de dados',
'o processo de projetos de dados': 'Research',
'o processo de transformação de dados': 'Data transformation',
'o que são redes neurais convolucionais': 'NN',
'o que é ETL': 'ETL',
'o que é digital analytics': 'Digital Analytics',
'o que é webscrapping': 'Fontes de dados',
'o recurso de SUBQUERY no SQL': 'SQL/Ferramenta',
'o tagueamento de base de dados': 'Bancos de dados',
'o tagueamento dos dados': 'Bancos de dados',
'o tratamento e proteção de dados pessoais na visão legal': 'LGPD',
'o treinamento de uma rede neural (forward propagation e backward propagation)': 'NN',
'o uso da função histórias do Tableau': 'Ferramenta',
'o uso das duas bibliotecas (bs4 + selenium) em conjunto': 'Fontes de dados/Ferramenta',
'o uso das funções JOIN': 'SQL/Ferramenta',
'o uso das funções: COALESCE. UCASE. LCASE. SUBSTRING. CONCAT. STR_TO_DATE': 'SQL/Ferramenta',
'o uso das funções: IF. CASE e SELECT DISTINCT': 'SQL/Ferramenta',
'o uso de filtros. grupos e sets no Tableau': 'Ferramenta',
'o uso de funções: INNER JOIN. LEFT JOIN. RIGHT JOIN. FULL OUTER JOIN. UNION': 'SQL/Ferramenta',
'o uso de histórias do usuário': 'Agile',
'o uso do Google Analytics como provedora de informação e insights para outras áreas': 'Ferramenta',
'o uso do Stories no Tableau': 'Storytelling/Ferramenta',
'o uso do Talend Data Preparation para fazer transformação de dados': 'Data transformation/Ferramenta',
'o uso do driver para controle de navegador': 'Fontes de dados',
'o uso dos conceitos de user experience (UX)': 'DataViz',
'objetivos da preparação de dados': 'Research',
'onde conseguimos dados e que tudo pode ser medido': 'Cultura de dados',
'onde estão os dados': 'Fontes de dados',
'opções de exportação. compartilhamento e publicação de visualizações no Tableau': 'Ferramenta',
'organização e obtenção de dados': 'Fontes de dados',
'os comandos DML: GROUP BY. HAVING': 'Ferramenta',
'os comandos DML: SELECT. WHERE. ORDER BY. LIMIT. GROUP BY': 'Ferramenta',
'os conceitos de análise e métricas para a estratégia digital': 'Research/Negócios',
'os diferentes tipos de gráficos': 'DataViz',
'os elementos visuais que tornam os gráficos mais eficientes': 'DataViz',
'os fatores que influenciam uma cultura data-driven': 'Cultura de dados',
'os objetivos de preparação de dados': 'Research',
'os operadores: LIKE. AND. OR. MAIOR. MENOR': 'Ferramenta',
'os papeis dentro de um time ágil (PO. Scrum Master. Devs)': 'Agile',
'os perfis multidisciplinar de um time de analytics': 'Management/Data Analytics',
'os pilares da agilidade': 'Agile',
'os processos de Extração. Carregamento (Load) e Transformação': 'Data transformation',
'os recursos do Google Analytics': 'Digital Analytics/Ferramenta',
'os sete pecados/condições da regressão (linearidade. multicolinearidade. distribuição normal. outliers. homocedasticidade. heterogeneidade. endogeneidade)': 'Regressão',
'os tipos de distribuição': 'Probabilidade',
'os tipos de redes neurais': 'NN/Algoritmo/ML',
'otimização': 'Otimização',
'otimização de Redes Neurais.': 'NN/ML',
'otimização de parâmetros': 'Otimização',
'outliers': 'Estatística descritiva',
'overfitting em modelos': 'Modelagem/Otimização',
'p-value': 'Estatística inferencial',
'pacotes de visualização': 'DataViz/Ferramenta',
'papeis dentro de um time ágil (PO. Scrum Master. Devs)': 'Agile',
'para o que serve a redução de dimensionalidade': 'Data compression',
'para que serve regularização': 'Regressão/Otimização',
'paradigma transacional': 'Data Analytics',
'parametrização': 'Ensembles/Otimização',
'parametrização de modelos de ensemble': 'Ensembles/Otimização',
'passar o conceito de atenção para uma rede neural': 'NN/ML',
'passo a passo de como rodar uma rede LSTM': 'NN/Algoritmo/ML',
'penalização de parâmetros': 'Otimização',
'perfis multidisciplinar de um time de analytics': 'Negócios/Management',
'perigos de não se entender o problema real ou o seu contexto': 'Research',
'pipeline': 'DevOps',
'pipeline de NLP': 'DevOps/NLP',
'pipelines': 'DevOps',
'planejamento e execução ágil': 'Agile',
'plotagens interativas com plotly': 'DataViz/Ferramenta',
'pontos de sucesso e fracasso em implantação ágil': 'Agile',
'por que fazer ETL': 'Data transformation',
'possibilidades de coleta de dados com scraping': 'Fontes de dados',
'possíveis aplicações de scraping para negócios': 'Fontes de dados/Aplicação',
'precificação': 'Negócios',
'predição de vendas': 'Modelagem/Predição',
'preparação de dados': 'Data preparation',
'probabilidade': 'Probabilidade',
'probabilidades': 'Probabilidade',
'processamento de clusterização em Python': 'Agrupamento/Ferramenta',
'processo de aplicação do machine learning': 'ML/Aplicação',
'processo de criação das Perguntas de Negócio': 'Negócios/Research',
'processo de data analytics': 'Data Analytics',
'processo de digital analytics': 'Data Analytics',
'processo de extração de dados': 'Fontes de dados',
'processo de mapeamento e implementação de digital analytics': 'Digital Analytics',
'processo de mentoria da Digital House': '?',
'processo de projetos de dados?': 'Management',
'projeto end-to-end': 'Management',
'projeto integrador': 'Aplicação',
'proposta de elaboração de uma Projeto End-to-End': 'Management',
'prática de regularização de modelos.': 'Modelagem/Otimização',
'prática emNLP': 'NLP/Aplicação',
'práticas ágeis': 'Agile',
'python básico': 'Programação/Ferramenta',
'python para machine learning': 'ML/Ferramenta',
'qual abordagem trazer para o problema escolhido': 'Research',
'quando priorizar Precisão ou Sensibilidade': 'Modelagem/Validação',
'quando usar um algoritmo de classificação': 'Classificação/Algoritmo/ML',
'quantificar visita em sites': 'Digital Analytics',
'quarta revolução industrial': 'History',
'quartil. percentil e boxplot': 'Estatística descritiva',
'quartis e percentil': 'Estatística descritiva',
'r2': 'Modelagem/Avaliação',
'realizar diferentes tipos de querys no SQL': 'Ferramenta',
'recomentação por comportamento de usuário': 'Sistemas de recomendação/ML',
'recomentação por similaridade das features (filmes. produtos. etc...)': 'Sistemas de recomendação/ML',
'rede convolucional': 'NN/Algoritmo/ML',
'regressão': 'Regressão',
'regressão linear': 'Regressão',
'regressão linear aplicada no excel': 'Regressão/Ferramenta',
'regressão linear simples': 'Regressão',
'regressão logística': 'Classificação',
'regressão multipla': 'Regressão',
'regressão múltipla': 'Regressão',
'regressões simples': 'Regressão',
'regularização': 'Modelagem/Otimização',
'regularização por Aumento no Conjunto de Dados': 'Modelagem/Otimização',
'relacionamento de Banco de Dados': 'Arquitetura de dados',
'relacionamentos de banco de dados': 'Arquitetura de dados',
'relacionamentos de bancos de dados': 'Arquitetura de dados',
'relação do tamanho da amostra e a convergência das distribuições': 'Estatística inferencial',
'relembrar o SQL': 'Ferramenta',
'request em um HTML': 'Fontes de dados/Ferramenta',
'requisitos das regressões linear': 'Regressão',
'resolução de problemas': 'Aplicação',
'resolução de problemas de negócios': 'Negócios/Aplicação',
'resoulçao de problemas reais com dados': 'Cultura de dados/Aplicação',
'responder perguntas de negócio com estatística': 'Negócios/Aplicação',
'ridge regression': 'Regressão/Otimização',
'rodar modelos de classificação': 'Classificação',
'rodar um algorítmo de ML': 'ML',
'scrapping': 'Fontes de dados',
'scrappy / minerar dados': 'Fontes de dados',
'separação de entidades e atributos': 'Fontes de dados',
'shap value': 'Modelagem/Interpretação',
'significancia da regressao': 'Regressão/Avaliação',
'significancia dos parametros': 'Regressão/Avaliação',
'sistemas de recomendação': 'Sistemas de recomendação/ML',
'skills para apresentação de análise': 'Storytelling',
'sobre conceitos de análise e métricas e sua importância negócios digitais': 'Métricas',
'sobre covariancia e correlação': 'Estatística descritiva',
'sobre desvio padrão e variância': 'Estatística descritiva',
'sobre os papeis e responsabilidades no SCRUM': 'Agile',
'solução de hipóteses com EDA': 'EDA',
'sprint': 'Agile',
'stacking': '?',
'storytelling': 'Storytelling',
'séries temporias': 'Séries temporais',
't-SNE': 'Data compression/Algoritmo/ML',
'tagueamento de base de dados': 'Bancos de dados',
'tecnicas de balanceamento com oversampling': 'Resampling',
'tecnicas de otimização (ex: grid search)': 'Otimização',
'teorema do limite central': 'Estatística inferencial',
'teste de Normalidade': 'Estatística inferencial',
'teste de normalidade': 'Estatística inferencial',
'teste t': 'Estatística inferencial',
'time series': 'Séries temporais',
'time series na prática.': 'Séries temporais/Aplicação',
'tipo de variáveis': 'Programação',
'tipos de coleta de dados': 'Fontes de dados',
'tipos de dados (quantitativos. categóricos | ordinais vs Nominais | Contínuos vs Discretos)': 'Estatística descritiva',
'tipos de distribuição': 'Probabilidade',
'tipos de gráficos e seus usos': 'DataViz',
'tipos de gráficos mais adequados para cada visualização': 'DataViz',
'tipos de variáveis (discretas e contínuas)': 'Programação',
'tomada decisões no SELECT': 'Ferramenta',
'tradroff entre viés e variância': 'Modelagem',
'transfer learning': 'DevOps',
'transformação de dados': 'Data transformation',
'união de tabelas': 'Ferramenta',
'uso das duas bibliotecas (bs4 + selenium) em conjunto': 'Fontes de dados/Ferramenta',
'uso das funcionalidades do PowerBI para o seu dia a dia de trabalho': 'Ferramenta/Aplicação',
'uso do pickle': 'DevOps/Ferramenta',
'uso dos comandos de união: INNER JOIN. LEFT JOIN. RIGHT JOIN': 'Ferramenta',
'uso e função do Google Analytics para a análise de dados': 'Digital Analytics/Ferramenta',
'uso e função do tagueamento (tags) para a análise de dados?': 'Digital Analytics',
'utilização da biblioteca selenium para navegar sites dinâmicos': 'Fontes de dados/Ferramenta',
'utilização da visualização de dados': 'DataViz',
'utilização de APIs': 'Fontes de dados',
'utilização de ARIMA e FBProphet': 'Séries temporais/Algoritmo',
'utilização de cada uma das distribuições': 'Probabilidade/Aplicação',
'utilização de soluções com API': 'DevOps',
'utilização de vários modelos em Ensembles': 'Ensembles',
'utlidades e aplicações do machine learning': 'ML',
'validação cruzada': 'Modelagem/Avaliação',
'valores e princípios ágeis': 'Agile',
'variabilidade': 'Modelagem',
'variáveis auto-correlacionadas': 'Séries temporais',
'variável aleatória discreta': 'Estatística descritiva',
'variável dependente / independente': 'Estatística descritiva',
'vetorização de palavras': 'NLP',
'visualização de dados': 'DataViz',
'viés': 'Research',
'viés cognitivo': 'Research',
'voting': 'Ensembles',
'web scraping': 'Fontes de dados',
'web scrapping': 'Fontes de dados',
'webscrapping': 'Fontes de dados',
'webscrapping com selenium': 'Fontes de dados',
'z-score': 'Estatística inferencial',
'Áreas de aplicação de sistemas de recomendação': 'Sistemas de recomendação/Aplicação/Algoritmo/ML',
'Árvores de decisão': 'Árvores de decisão/Algoritmo/ML',
'Ética': 'LGPD',
'Índice de confiança e intervalo de confiança': 'Estatístia inferencial'
}

def normalize_component(component):
	nc = COMPONENT_MAP[component]

	return nc if nc else None